from tkinter import *
window1=Tk()
window1.title('notpad')
window1.geometry('500x500')
window1.configure(bg='light blue')
e1=Entry(bg='grey',fg='white',width=50)
l1=Label(text='Convert inches into cm',fg='black',bg='light grey',height=2,width=25)
b1=Button(text='Convert',fg='blue',bg='light green',height=2,width=10)
l2=Label(text='Answer',fg='black',bg='light grey',height=2,width=25)
def convert(6)
l1.pack()
e1.pack()
b1.pack()
l2.pack()
e1.place(x=90,y=60)
b1.place(x=200,y=110)
l2.place(x=150,y=250)
window1.mainloop()