from tkinter import *
window1=Tk()
window1.title('notpad')
window1.geometry('500x500')
window1.configure(bg='blue')
l1=Label(text='adams lab',fg='red',bg='yellow',height=3,width=10)
b1=Button(text='clik on me',fg='yellow',bg='green',height=3,width=10)
e1=Entry(bg='blue',fg='white',width=50)
l1.pack()
e1.pack()
b1.pack()
f1=Frame(master=window1,bg='yellow',height=200,width=200,relief='groove',borderwidth=5)
f1.place(x=300,y=300)
window1.mainloop()